server:
  http:
    addr: 0.0.0.0:80 # Project access port number
data:
    driver: "mysql" # Default database driver is mysql
    # todo 数据库名字需要换一下
    connection: "root:123456@tcp(127.0.0.1:3306)/answer?charset=utf8mb4&parseTime=True" # MySQL database connection address
redis:
  addr: 127.0.0.1:6379
  poolSize: 20
  maxIdle:  20
  timeout:  10
i18n:
  bundle_dir: "/data/i18n" # Internationalized file storage directory
service_config:
  secret_key: "lawyer" # encryption key
  upload_path: "/data/uploads" # upload directory
