[server]
addr = ":8081"
mode = "release"

[log]
level = "info"
dir = "./logs"

[email]
smtpHost = "smtp.gmail.com"
smtpPort = 587
smtpUsername = "jackzhi4716@gmail.com"
smtpPassword = "tkft cwpv tffr hefa"

